# Generated by Django 2.2.3 on 2019-07-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_file', models.CharField(max_length=255)),
                ('tanggal', models.DateField(auto_now=True)),
                ('tanggalinput', models.DateField()),
                ('jam', models.TimeField(auto_now=True)),
                ('jaminput', models.TimeField()),
                ('integ', models.IntegerField()),
                ('isi', models.TextField()),
                ('tempat', models.URLField()),
            ],
        ),
    ]
